[package]
name = "rust_serialization_benchmark"
version = "0.1.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abomonation = "0.7"
abomonation_derive = "0.5"
bcs = "0.1.3"
bincode = "1.3"
borsh = "0.8"
bytecheck = "0.4"
capnp = "0.14"
criterion = "0.3"
flatbuffers = "0.8"
hex = "0.4.3"
libflate = "1.0"
nachricht-serde = "0.2"
postcard = { version = "0.5", features = ["alloc"] }
prost = "0.7"
rand = "0.8"
rkyv = { version = "~0.6.1", features = ["validation"] }
rmp-serde = "0.15"
ron = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.5"
serde_cbor = "0.11"
serde_json = "1.0"
speedy = "0.7"

[dev-dependencies]
rand_pcg = "0.3"

[build-dependencies]
capnp = "0.14"
capnpc = "0.14"
prost-build = { version = "0.7" }

[[bench]]
name = "bench"
harness = false
